### ISSUE TITLE
Existe un grupo llamado usuario, pero no deveria existir.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#10]
![image](https://user-images.githubusercontent.com/60109826/125109409-eec5cc80-e0a8-11eb-9ef4-a1eb8d89df85.png)

**Comment by giovannizvl** [comment]
S borro el id de Cliente, desde la base de datos asi que no aparece
![Captura de pantalla (226)](https://user-images.githubusercontent.com/60110427/125650981-ea01f055-0f0f-438d-825b-aae7d3f3c6b1.png)
