### ISSUE TITLE
Why We Use Electoral College, Not Popular Vote.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#11]
![image](https://user-images.githubusercontent.com/60109826/125111397-78769980-e0ab-11eb-8de5-e4a190558a5a.png)

**Comment by giovannizvl** [comment]
Se corrigi
![Captura de pantalla (227)](https://user-images.githubusercontent.com/60110427/125651276-f7306b8d-ee73-46e9-9c7b-c84742272145.png)
o el texto
