### ISSUE TITLE
Diseño responsivo.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#12]
![image](https://user-images.githubusercontent.com/60109826/125111934-22562600-e0ac-11eb-9b9d-432b662b672a.png)

**Comment by giovannizvl** [comment]
Se agrego el diseño movil para la pantalla solicitud de alta

![Captura de pantalla (228)](https://user-images.githubusercontent.com/60110427/125651542-896ecd19-c05e-467f-9b0e-aa17cd1a4902.png)
