### ISSUE TITLE
correo de solicitud de alta.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#13]
El correo debe tener datos y link para el alta del usuario.

![image](https://user-images.githubusercontent.com/60109826/125112804-45cda080-e0ad-11eb-80a9-2eb78a34aa24.png)

**Comment by giovannizvl** [comment]
El correo quedo de la siguiente manera con el link

![Captura de pantalla (229)](https://user-images.githubusercontent.com/60110427/125652981-edaeb157-6211-45b0-be17-7b6b73d48aab.png)
