### ISSUE TITLE
no pasa nada cuando doy enter.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#14]
intuitivamente siempre damos enter en los formularios, aun que sea servicio hay manera de simular el comportamiento.

![image](https://user-images.githubusercontent.com/60109826/125115036-6814ed80-e0b0-11eb-90cf-a1b7726f9b62.png)

**Comment by Sergio-hue** [comment]
Se agrego una funcion de jquery en la vista de Login

**Comment by Sergio-hue** [comment]
![imagen](https://user-images.githubusercontent.com/60446852/125660842-77139d2c-0ab5-4430-9014-cf2576dc62ec.png)
