### ISSUE TITLE
A donde llega la foto.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#15]
No es claro si se esta guardando o no la foto y si se esta guardando hay que utilizarla para avatar.

![image](https://user-images.githubusercontent.com/60109826/125115248-b1653d00-e0b0-11eb-8c99-b9259a72769d.png)

**Comment by Sergio-hue** [comment]
Por el momento se deshabilita la foto debido a que no se ocupa la foto en este momento

![imagen](https://user-images.githubusercontent.com/60446852/125828344-156f3a4c-6884-4baf-87e4-ff8d16f076ec.png)
