### ISSUE TITLE
Asociado aceptado no se puede logear.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#17]
Usuario: ulises.rodriguez@webcorp.com.mx
Pass: Polimorfism0

**Comment by Sergio-hue** [comment]
Se hizo varias pruebas y si registra he inicia sesion correctamente

**Comment by Sergio-hue** [comment]
![imagen](https://user-images.githubusercontent.com/60446852/125661560-e3652737-1464-4a40-9c5b-b633b80b46f8.png)

Ejemplo de asociado iniciando sesion
