### ISSUE TITLE
title en asociados.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#18]
![image](https://user-images.githubusercontent.com/60109826/125117106-5254f780-e0b3-11eb-82ce-febec94c005f.png)

**Comment by Sergio-hue** [comment]
Cuando se ingresa a los modulos estos con el token busca el id_group del usuario y asi dependiendo a cual grupo pertenece el el titulo solo se agregara si es socio o back office

**Comment by Sergio-hue** [comment]
![imagen](https://user-images.githubusercontent.com/60446852/125660987-a4463d60-c7cf-4755-b1b8-db00b921d194.png)
