### ISSUE TITLE
modal muy pequeño.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#19]
![image](https://user-images.githubusercontent.com/60109826/125117256-9516cf80-e0b3-11eb-8270-bc75946655f2.png)

**Comment by Sergio-hue** [comment]
Solo se cambio el tamaño del modal

**Comment by Sergio-hue** [comment]
![imagen](https://user-images.githubusercontent.com/60446852/125661655-ab3a6081-2d6d-414c-8b07-40fbb1c2a534.png)
