### ISSUE TITLE
Ordenar por fecha descendente de mas nuevo a mas viejo.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#20]
![image](https://user-images.githubusercontent.com/60109826/125117601-18382580-e0b4-11eb-8c0a-202c5be021f8.png)

**Comment by Sergio-hue** [comment]
En datatable se agrega [1,ASC] a las opciones de jquery esto hace que se ordenen del mas viejo al mas nuevo y 1 es la columna a lo cual se va a ordenar, en este caso fecha de entrega
