### ISSUE TITLE
No muestra detalles de pedido.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#21]
![image](https://user-images.githubusercontent.com/60109826/125117940-91377d00-e0b4-11eb-8139-1df4cb18813d.png)

**Comment by Sergio-hue** [comment]
En el boton de detalles esta deshabilitado debido a que como tal no hay una entrega de evidencia , se deshabilita pero al momento de dar click a los que están disponibles , si lo desplega correctamente

**Comment by Sergio-hue** [comment]
Se quita la opcion disable del input y asi muestra el modal con los detalles del pedido
Hay 2 tipos de visualizacion del modal
1->modal sin evidencia de foto
2->modal con evidencia
