### ISSUE TITLE
Vista de chofer.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#22]
![image](https://user-images.githubusercontent.com/60109826/125118540-79acc400-e0b5-11eb-9dcf-d972c5a263e0.png)

**Comment by DianaAG** [comment]
![imagen](https://user-images.githubusercontent.com/43766264/125654264-cc794326-7400-4d22-bf97-2fc8b70c0ed8.png)
![imagen](https://user-images.githubusercontent.com/43766264/125654438-9a271b67-0303-4700-844c-0e8986d5584d.png)

Deleted use of left header and created header specifically to fix the whitespace issue, added style modification to fix leftover whitespace
