### ISSUE TITLE
login responsivo

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#23]
La imagen debe cubrir toda la pantalla y los elementos deben ir centrados.

![image](https://user-images.githubusercontent.com/60109826/125640712-9d1a49c4-1f1a-496f-8614-f38463281e76.png)

**Comment by Sergio-hue** [comment]
Necesito la nueva imagen para responsivo debido a que la linea azul es parte de la imagen

**Comment by Sergio-hue** [comment]
![imagen](https://user-images.githubusercontent.com/60446852/125696979-e7fbbce4-18f0-4b60-b15e-18f144264784.png)
