### ISSUE TITLE
Tablas desfazadas

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#24]
![image](https://user-images.githubusercontent.com/60109826/125641555-dc0682fc-2806-41ea-8943-4f8816cfc000.png)

**Comment by giovannizvl** [comment]
Correccion de las tabla desfazada, se agrefo el scroll

![Captura de pantalla (230)](https://user-images.githubusercontent.com/60110427/125653570-4f6dbbc6-d7ba-4a0b-8a4f-e671bb1c87cc.png)
