### ISSUE TITLE
Nombre de negocio en actualizar

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#25]
Se agrego el nombre de negocio al registrarlo pero no se agrego en el formalurio de edicion, ni en la tabla de socios por autorizar.

![image](https://user-images.githubusercontent.com/60109826/125644036-e39df799-f64f-4f03-b44f-d2db3b058c6c.png)

![image](https://user-images.githubusercontent.com/60109826/125644335-1d93342c-ebd2-4b8b-9935-d8259aa85e5c.png)

**Comment by giovannizvl** [comment]
Se agrego la columna del nombre del negocio en socios por autorizar
![Captura de pantalla (231)](https://user-images.githubusercontent.com/60110427/125655331-276798a3-3a2b-412c-b922-92f467ba06e3.png)

El la tabla de Bo negocios se agrego el input en el modal y en la tabla se agrego tambien el nombre del negocio
![Captura de pantalla (232)](https://user-images.githubusercontent.com/60110427/125657491-96e97f37-61d0-47ef-8cc4-38a933509b73.png)
![Captura de pantalla (233)](https://user-images.githubusercontent.com/60110427/125657492-b12dce9c-cca6-437c-968b-7fe1d70a7fd2.png)
