### ISSUE TITLE
Cierra session inesperadamente y no manda nuevamente a login

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#26]
![image](https://user-images.githubusercontent.com/60109826/125646774-567809ff-c60d-4cdd-aad8-0a009301c075.png)

**Comment by giovannizvl** [comment]
SE creo una doble validacion cuando existe sesion y cambia el token manda al login y cuando no hay sesion no se pueda acceder directamente a la vista
