### ISSUE TITLE
Confirmacion de password y eliminar combo de seleccion de tipo de perfil

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#27]
![image](https://user-images.githubusercontent.com/60109826/125664034-0c611e7b-e692-4a3a-bcce-31b1e892fd73.png)

**Comment by giovannizvl** [comment]
![Screenshot_2021-08-30 Starlight](https://user-images.githubusercontent.com/60110427/131381100-23a41ef5-9f49-45ca-bcb7-612a540f3350.png)
![Screenshot_2021-08-30 Starlight(1)](https://user-images.githubusercontent.com/60110427/131381103-9df3896b-8c07-4593-b0f7-cb9122f6d37c.png)
