### ISSUE TITLE
Sin Sucursal.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#31]
![image](https://user-images.githubusercontent.com/60109826/125668299-7b475a37-ff76-42dd-9540-bf3041893164.png)

**Comment by Sergio-hue** [comment]
![imagen](https://user-images.githubusercontent.com/60446852/126004126-bec9e70d-fb42-4faa-ae03-43c4bd2059a8.png)

Se agrega la matiz por default
