### ISSUE TITLE
Agregar pedidos sin sucursal.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#32]
![image](https://user-images.githubusercontent.com/60109826/125668726-c74f9960-b917-4264-a145-7c49512d6136.png)

**Comment by Sergio-hue** [comment]
![imagen](https://user-images.githubusercontent.com/60446852/126004252-24c5cfc9-738f-4d14-8f31-2cdb1f8a0159.png)

Se agrega pedidos con sucursal por default
