### ISSUE TITLE
Error en validacion de horario.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#33]
![image](https://user-images.githubusercontent.com/60109826/125668887-e8c5f4bc-06ba-42df-ab93-a64c8189e58f.png)

**Comment by Sergio-hue** [comment]
![imagen](https://user-images.githubusercontent.com/60446852/125827903-95331025-ec57-4534-82e3-4c862550b761.png)

Va de acuerdo a la hora 
Si se cancela despues de las 8 va con cargo
