### ISSUE TITLE
Eliminar pedidos y mantener registro para BO si hubo cargo o no hubo cargo.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#34]
![image](https://user-images.githubusercontent.com/60109826/125670077-6cf81aa9-4d57-4745-98b0-730e4e8a9ca9.png)

**Comment by Sergio-hue** [comment]
Eliminamos pastel
![imagen](https://user-images.githubusercontent.com/60446852/125826964-6ee4facd-4d9a-4450-9adb-3ac96c18e3fa.png)

**Comment by Sergio-hue** [comment]
![imagen](https://user-images.githubusercontent.com/60446852/125827016-43bc9232-6c2b-48e6-a80f-a52df887d745.png)

**Comment by Sergio-hue** [comment]
![imagen](https://user-images.githubusercontent.com/60446852/125827094-676bb25d-734f-4968-bdf4-825897b542e0.png)

Mostrara un mensaje sin cargo y este se guardara en la base
