### ISSUE TITLE
Agregar nivel de gestores en sucursales.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#35]
![image](https://user-images.githubusercontent.com/60109826/125671243-20ffe14e-e6d6-4cd9-8647-263960b49ff9.png)

**Comment by giovannizvl** [comment]
Se agrego boton para Gestores
![Captura de pantalla (247)](https://user-images.githubusercontent.com/60110427/125864201-4293ce20-0660-43e7-9326-b57aaea0c9c8.png)
![Captura de pantalla (248)](https://user-images.githubusercontent.com/60110427/125864367-eaa7d91e-3ec9-45ae-8907-878573563260.png)
![Captura de pantalla (249)](https://user-images.githubusercontent.com/60110427/125864368-c29c8788-c887-44c2-9fcd-2505e01e5d16.png)
![Captura de pantalla (250)](https://user-images.githubusercontent.com/60110427/125864370-fd78a28f-1be3-451d-8ebe-07cf6905364a.png)
![Captura de pantalla (251)](https://user-images.githubusercontent.com/60110427/125864371-304a098c-52bf-4b68-a238-2f169aba8635.png)
![Captura de pantalla (252)](https://user-images.githubusercontent.com/60110427/125864372-4fd5d7c3-039a-4074-b7fb-9c9df2a65103.png)
![Captura de pantalla (253)](https://user-images.githubusercontent.com/60110427/125864373-8008cd22-0bad-4452-bb13-32d9b843a995.png)
