### ISSUE TITLE
Cuando se crea nuevo usuario trae valores por default

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#36]
![image](https://user-images.githubusercontent.com/60109826/125697353-493a87c0-4265-4f6d-9671-148ba3572fc3.png)

**Comment by Sergio-hue** [comment]
![imagen](https://user-images.githubusercontent.com/60446852/126004392-f9e827f0-eb75-452c-8f0a-fb223beb86df.png)
