### ISSUE TITLE
Estilos de tabla cuando no hay registros.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#37]
![image](https://user-images.githubusercontent.com/60109826/125698522-5bcfda81-50d0-4dca-aaa6-61c7d17d02b8.png)

**Comment by giovannizvl** [comment]
correcion de la tabla
![Captura de pantalla (257)](https://user-images.githubusercontent.com/60110427/125865717-bf507155-0750-4856-ae61-af4f62b115f4.png)
