### ISSUE TITLE
Pedidos en ruta estilos de tabla vacia.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#38]
![image](https://user-images.githubusercontent.com/60109826/125698646-c0a81b42-6095-40b6-a3c2-3c3e1afd0ed6.png)

**Comment by giovannizvl** [comment]
Se relizo la correcion en los headers de la tabla
![Captura de pantalla (256)](https://user-images.githubusercontent.com/60110427/125865393-e668e8f9-8b52-4824-a00c-c20125993884.png)
