### ISSUE TITLE
Tablas descuadradas y leyenda "starlight"

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#40]
Cuando falta un dato las tablas pierden forma.

Ocultar la leyenda Starlight.

![image](https://user-images.githubusercontent.com/60109826/130492180-359758ef-c168-4fed-9f59-27147ef88042.png)

**Comment by Sergio-hue** [comment]
![image](https://user-images.githubusercontent.com/60446852/130674028-704df971-989c-4ccd-acb9-bcb8543141f6.png)
