### ISSUE TITLE
Data table incompleta.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#42]
sin barra de busqueda ni opciones de ordenamiento.

![image](https://user-images.githubusercontent.com/60109826/130492980-ade89da1-3b23-4820-ad22-d6938296ff4f.png)

**Comment by Sergio-hue** [comment]
![image](https://user-images.githubusercontent.com/60446852/130688445-e13d6871-a5c1-4f6e-b504-397a6d6bbf71.png)
