### ISSUE TITLE
data table incompleta.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#43]
Sin opciones de ordenamiento.

![image](https://user-images.githubusercontent.com/60109826/130493322-0db4b6ed-b9c6-4354-8954-988a085c5484.png)

**Comment by giovannizvl** [comment]
![Captura de pantalla (314)](https://user-images.githubusercontent.com/60110427/130678283-1b3c1326-8f0c-4928-ba4a-448c4e5fa73d.png)
