### ISSUE TITLE
ajuste de estilo en pantalla gestor.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#45]
Boton para cerrar menu queda al centro.

![image](https://user-images.githubusercontent.com/60109826/130494827-2aa58a33-b5b8-4963-b847-51d9d8c1171b.png)

**Comment by Sergio-hue** [comment]
![image](https://user-images.githubusercontent.com/60446852/130687344-71333385-4653-4bb4-afcb-eaf9baeefabe.png)
