### ISSUE TITLE
validar que se haya seleccionado chofer.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#48]
Si no seleccionas chofer no envia mensaje ni muestra ninguna alerta.

![image](https://user-images.githubusercontent.com/60109826/130496092-f5e2d423-df07-47bc-a7cf-44c0b16d6549.png)

**Comment by giovannizvl** [comment]
![Captura de pantalla (312)](https://user-images.githubusercontent.com/60110427/130676045-d8537b96-c7e7-49cd-8655-b2f86c2a1b54.png)
