### ISSUE TITLE
Data table incompleta, pedidos en ruta.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#49]
![image](https://user-images.githubusercontent.com/60109826/130496447-ab8e5b0d-3c76-4be7-8adc-83e865ea0b10.png)

**Comment by giovannizvl** [comment]
![Captura de pantalla (316)](https://user-images.githubusercontent.com/60110427/130678891-bd025588-2589-4100-99a7-bb90440d3848.png)
