### ISSUE TITLE
no muestra mensaje de error alguno.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#50]
pantalla de detalles se queda cargando en pedidos entregados.

![image](https://user-images.githubusercontent.com/60109826/130496699-3919f190-5157-4e74-80c3-ab8749b7b955.png)

**Comment by giovannizvl** [comment]
este error solo aparece con los pedidos antiguos, cuando no estaba bien definida la tabla, no deben aparecer si no se a realizado la entrega
