### ISSUE TITLE
No muestra todos los estatus.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#51]
Mostrar las dos imagenes.

![image](https://user-images.githubusercontent.com/60109826/130498935-53630004-6a0b-43b1-8c54-1150b68c44aa.png)

**Comment by Sergio-hue** [comment]
![image](https://user-images.githubusercontent.com/60446852/130694221-58e6f33b-f208-4135-a922-3f230c692fbf.png)
