### ISSUE TITLE
se ingresan registros sin datos en socios por autorizar.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#53]
![WhatsApp Image 2021-08-23 at 15 53 11](https://user-images.githubusercontent.com/60109826/130518074-869f7ef1-e245-4867-8cb8-29ecbc9cebc0.jpeg)

**Comment by giovannizvl** [comment]
Se realizo validaciones de alta, para no mandar campos vacios
![Captura de pantalla (319)](https://user-images.githubusercontent.com/60110427/130692401-a1d4d5bd-a9d0-4219-9065-f0cf913fe2bd.png)
