### ISSUE TITLE
Multiples direcciones de Inicio de Ruta

### ISSUE THREAD

**Issue by rodrigohdezc** [DevWebcorp/Delivanto#56]
Al buscar dirección de inicio de ruta localiza el punto en el mapa, si el punto lo movemos se actualiza la dirección, PERO, si la dirección la actualizo y doy nuevamente buscar dirección AGREGA un nuevo punto en el mapa, así tantas veces modifique la dirección escrita y de buscar dirección

![Screenshot_28](https://user-images.githubusercontent.com/72474096/130523576-c2477bf9-1874-46a6-aea6-49a0e8038a1d.jpg)

**Comment by giovannizvl** [comment]
validacion de marcador 
![Captura de pantalla (307)](https://user-images.githubusercontent.com/60110427/130665198-89527c80-f311-475a-8891-2392b22bd38b.png)
![Captura de pantalla (308)](https://user-images.githubusercontent.com/60110427/130665204-9551e7af-4fdf-41a4-a1d3-adc82d540f13.png)

**Comment by giovannizvl** [comment]
se corrio lo del marcador
