### ISSUE TITLE
Cambia grupo al actualizar

### ISSUE THREAD

**Issue by rodrigohdezc** [DevWebcorp/Delivanto#57]
Al actualizar el usuario no selecciona el grupo al que pertenece

![Screenshot_30](https://user-images.githubusercontent.com/72474096/130528899-ab7fbc5c-8e49-480b-a73a-c103d05ab193.jpg)

**Comment by Sergio-hue** [comment]
![image](https://user-images.githubusercontent.com/60446852/130696424-224c25db-984f-4a74-889e-bd781f82ff99.png)
