### ISSUE TITLE
errores inesperados en detalles de gestores.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#7]
Con algunos si funciona, independientemente de si es por que son datos de prueba y falta alguno, se tienen que cachar errores y enviar notificaciones y/o alertas.

![image](https://user-images.githubusercontent.com/60109826/125108638-ed47d480-e0a7-11eb-8197-60c852e611c4.png)
![image](https://user-images.githubusercontent.com/60109826/125108657-f46ee280-e0a7-11eb-80e7-e6fd6604d621.png)
![image](https://user-images.githubusercontent.com/60109826/125108699-03ee2b80-e0a8-11eb-84bf-4abf39256ee0.png)

**Comment by Sergio-hue** [comment]
![imagen](https://user-images.githubusercontent.com/60446852/125682823-29a4ec10-74be-4a4b-aa09-6166af296e03.png)

Se corrige ahora se muestra los gestores de el mismo  y en back office mostrara todos los gestores

**Comment by Sergio-hue** [comment]
![imagen](https://user-images.githubusercontent.com/60446852/125682916-7d22abb6-cc34-405d-ac70-7ebebb23aa26.png)
