### ISSUE TITLE
error en sucursales, no muestra detalles.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#8]
![image](https://user-images.githubusercontent.com/60109826/125109014-6b0be000-e0a8-11eb-9273-d5eaeaedac6f.png)
![image](https://user-images.githubusercontent.com/60109826/125109050-73fcb180-e0a8-11eb-9afd-aba51103d3db.png)

**Comment by Sergio-hue** [comment]
![imagen](https://user-images.githubusercontent.com/60446852/125839196-877099fa-59df-4054-943a-400cae374a40.png)
