### ISSUE TITLE
Confirma eliminacion de sucursal, pero no elimina.

### ISSUE THREAD

**Issue by DevWebcorp** [DevWebcorp/Delivanto#9]
![image](https://user-images.githubusercontent.com/60109826/125109281-c3db7880-e0a8-11eb-9404-ec88311ee2b9.png)

**Comment by Sergio-hue** [comment]
Elimina el sucursal correctamente
![imagen](https://user-images.githubusercontent.com/60446852/125663244-f9f85dfc-75b6-4199-8eac-3d58dbff0906.png)
